const { contextBridge, ipcRenderer, webUtils, clipboard } = require('electron');
contextBridge.exposeInMainWorld('api', {
  clipboardWriteText: (text) => clipboard.writeText(String(text ?? '')),
  clipboardReadText: () => clipboard.readText(),
  getConfig: () => ipcRenderer.invoke('config:get'),
  readTree: (args) => ipcRenderer.invoke('tree:read', args),
  treeSignature: (args) => ipcRenderer.invoke('tree:signature', args),
  readFile: (args) => ipcRenderer.invoke('file:read', args),
  writeFile: (args) => ipcRenderer.invoke('file:write', args),
  move: (args) => ipcRenderer.invoke('fs:move', args),
  createFsItem: (args) => ipcRenderer.invoke('fs:create', args),
  renameFsItem: (args) => ipcRenderer.invoke('fs:rename', args),
  deleteFsItem: (args) => ipcRenderer.invoke('fs:delete', args),
  revealInExplorer: (args) => ipcRenderer.invoke('fs:reveal', args),
  copyExternal: (args) => ipcRenderer.invoke('fs:copyExternal', args),
  getPathForFile: (file) => webUtils.getPathForFile(file),
  pickFolder: () => ipcRenderer.invoke('folder:pick'),
  openWorkspace: () => ipcRenderer.invoke('workspace:openDirectory'),
  openWorkspaceFile: () => ipcRenderer.invoke('workspace:openFile'),
  resyncWorkspace: (payload) => ipcRenderer.invoke('workspace:resync', payload),
  newWindow: (workspace) => ipcRenderer.invoke('window:new', workspace),
  terminalStart: (args) => ipcRenderer.send('terminal:start', args),
  terminalWrite: (data) => ipcRenderer.send('terminal:write', data),
  terminalResize: (size) => ipcRenderer.send('terminal:resize', size),
  onTerminalData: (cb) => ipcRenderer.on('terminal:data', (_event, data) => cb(data)),
  onWorkspaceChanged: (cb) => ipcRenderer.on('workspace:changed', (_event, data) => cb(data)),
  onMenuSaveFile: (cb) => ipcRenderer.on('menu:saveFile', () => cb()),
  onMenuRefreshTree: (cb) => ipcRenderer.on('menu:refreshTree', () => cb()),
  onLangChanged: (cb) => ipcRenderer.on('lang:changed', (_event, lang) => cb(lang))
});
