const { contextBridge, ipcRenderer, webUtils } = require('electron');
contextBridge.exposeInMainWorld('api', {
  // The `clipboard` module is unavailable in a sandboxed preload, so go through the main process.
  clipboardWriteText: (text) => ipcRenderer.sendSync('clipboard:writeText', String(text ?? '')),
  clipboardReadText: () => ipcRenderer.sendSync('clipboard:readText'),
  clipboardHasImage: () => ipcRenderer.sendSync('clipboard:hasImage'),
  saveClipboardImage: (args) => ipcRenderer.invoke('fs:saveClipboardImage', args),
  pushImageToWsl: (args) => ipcRenderer.invoke('clipboard:pushImageToWsl', args),
  getConfig: () => ipcRenderer.invoke('config:get'),
  readTree: (args) => ipcRenderer.invoke('tree:read', args),
  treeSignature: (args) => ipcRenderer.invoke('tree:signature', args),
  readFile: (args) => ipcRenderer.invoke('file:read', args),
  statFile: (args) => ipcRenderer.invoke('file:stat', args),
  gitInfo: (args) => ipcRenderer.invoke('git:info', args),
  openExternal: (url) => ipcRenderer.invoke('shell:openExternal', url),
  readImage: (args) => ipcRenderer.invoke('file:readImage', args),
  writeFile: (args) => ipcRenderer.invoke('file:write', args),
  move: (args) => ipcRenderer.invoke('fs:move', args),
  createFsItem: (args) => ipcRenderer.invoke('fs:create', args),
  renameFsItem: (args) => ipcRenderer.invoke('fs:rename', args),
  deleteFsItem: (args) => ipcRenderer.invoke('fs:delete', args),
  revealInExplorer: (args) => ipcRenderer.invoke('fs:reveal', args),
  copyExternal: (args) => ipcRenderer.invoke('fs:copyExternal', args),
  getPathForFile: (file) => webUtils.getPathForFile(file),
  pickFolder: () => ipcRenderer.invoke('folder:pick'),
  openWorkspace: () => ipcRenderer.invoke('workspace:openDirectory'),
  openWorkspaceFile: () => ipcRenderer.invoke('workspace:openFile'),
  cloneRepo: (args) => ipcRenderer.invoke('workspace:clone', args),
  recentWorkspaces: () => ipcRenderer.invoke('workspace:recent'),
  openRecentWorkspace: (args) => ipcRenderer.invoke('workspace:openRecent', args),
  sessionSave: (args) => ipcRenderer.send('session:save', args),
  sessionGet: (args) => ipcRenderer.invoke('session:get', args),
  resyncWorkspace: (payload) => ipcRenderer.invoke('workspace:resync', payload),
  newWindow: (workspace) => ipcRenderer.invoke('window:new', workspace),
  popupMenu: (pos) => ipcRenderer.send('menu:popup', pos),
  terminalStart: (args) => ipcRenderer.send('terminal:start', args),
  terminalWrite: (payload) => ipcRenderer.send('terminal:write', payload),
  terminalResize: (payload) => ipcRenderer.send('terminal:resize', payload),
  terminalClose: (payload) => ipcRenderer.send('terminal:close', payload),
  onTerminalData: (cb) => ipcRenderer.on('terminal:data', (_event, payload) => cb(payload)),
  onTerminalExit: (cb) => ipcRenderer.on('terminal:exit', (_event, payload) => cb(payload && payload.id)),
  onWorkspaceChanged: (cb) => ipcRenderer.on('workspace:changed', (_event, data) => cb(data)),
  onMenuRefreshTree: (cb) => ipcRenderer.on('menu:refreshTree', () => cb()),
  onMenuRestartTerminal: (cb) => ipcRenderer.on('menu:restartTerminal', () => cb()),
  onLangChanged: (cb) => ipcRenderer.on('lang:changed', (_event, lang) => cb(lang)),
  onUpdateProgress: (cb) => ipcRenderer.on('update:progress', (_event, payload) => cb(payload)),
  windowMinimize: () => ipcRenderer.send('window:minimize'),
  windowToggleMaximize: () => ipcRenderer.send('window:toggleMaximize'),
  windowClose: () => ipcRenderer.send('window:close'),
  onWindowMaximized: (cb) => ipcRenderer.on('window:maximized', (_event, isMax) => cb(isMax))
});
